baseURL = 'https://cbull.dev/'
languageCode = 'en-us'
title = 'Christian Bull'
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Christian Bull's personal site"
  copyright = "Copyright © 2021 Christian Bull"
  dark = "on"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "blog"
    title = "posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "contact"
    url = "/contact/"
    weight = 30

[permalinks]
  posts = "/:title/"