apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cbull-dev
  name: cbull-dev
  labels:
    app: cbull-dev
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cbull-dev
  template:
    metadata:
      labels:
        app: cbull-dev
    spec:
      containers:
        - name: cbull-dev
          image: csbull55/cbull-dev:main-155a2ac56b0a68984c7766b2e42298eba0a04ab7
