name: deploy

on:
  workflow_run:
    workflows: ["buildAndPush"]
    branches: [main]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Christian-Bull/cbull-dev-infra
          token: ${{ secrets.CBULL_PAT }}
        
      - name: set env vars
        run: |
          echo "SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          
      - name: update deployment spec
        run: |
          sed 's/SED_imageName/${{ env.GITHUB_REF_NAME }}-${{ env.SHA }}/g' manifests/.templates/deployment.yml > manifests/deployment.yml

      - name: Create Pull Request
        uses: EndBug/add-and-commit@v9
        with:
          branch: main

